version: '3'
services:
  ngnix:
    image: nginx:latest
    container_name: nginx-for-blue-green
    ports:
      - "5800:5800"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  blue-green:
    image: localhost:5000/bridge/blue-green:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5800"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - <absolute path to this folder>:/docker-compose
    command: node /app/src/index.js
