version: '3'
services:
  watcher:
    build: .
    container_name: chtbridge
    environment:
      - FOO
    ports:
      - "5100:5100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../docker-compose:/destination
      - ../services:/source
    command: node /app/src/index.js
