version: '3'
services:
  self-upgrading-container:
    image: localhost:5000/bridge/self-upgrading-container:latest
    restart: always
    networks:
      - cht-net
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5800-5801:5800"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/diana/projects/bridge/self-upgrading-container/docker-compose:/docker-compose:ro
    command: node /app/src/index.js

networks:
  cht-net:
    name: cht-net
